name: Build and Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Debug - List files before build
        run: ls -l

      - name: Build Vue.js project
        run: npm run build

      - name: Debug - List files after build
        run: ls -l

      - name: Verify dist directory
        run: |
          if [ ! -d "dist" ]; then
            echo "Error: 'dist' directory does not exist."
            exit 1
          fi

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.2.0
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "dist"
